name: escribe-suite
base: core22
version: '2.0'
summary: Configuring, monitoring, and modifying the operation of your DNA device
description: |
   EScribe Suite is a collection of software for configuring, monitoring, and modifying the operation of your DNA device.
   It connects to your DNA device using the USB port.
grade: stable
confinement: strict
architectures: [ amd64, arm64 ]

apps:
  escribe-suite:
    command: ./launch-escribe-suite
    plugs: [home, x11, desktop, raw-usb, hardware-observe, shared-memory ]
    environment:
        MONO_CONFIG: "$SNAP/etc/mono/config"
        MONO_GAC_PREFIX: "$SNAP/usr/lib/mono/gac"
        MONO_PATH: "$SNAP/usr/lib/cli/atk-sharp-2.0:$SNAP/usr/lib/cli/gdk-sharp-2.0:$SNAP/usr/lib/cli/glib-sharp-2.0:$SNAP/usr/lib/cli/gtk-dotnet-2.0:$SNAP/usr/lib/cli/gtk-sharp-2.0:$SNAP/usr/lib/cli/pango-sharp-2.0"
        DISABLE_WAYLAND: 1
parts:
  escribe-suite:
    source: ./escribe-suite/
    source-type: local
    plugin: dump
    override-pull: |
       craftctl default
       cp -f /root/project/get-escribe.sh ./
    override-prime: |
       craftctl default
       chmod a+rx ./launch-escribe-suite
       find . -type f -exec chmod a+r {} \;
       find . -type d -exec chmod a+rx {} \;
    build-packages:
      - unzip
      - wget
    stage-packages:
      - desktop-file-utils
      - ca-certificates-mono
      - libgtk2.0-0
      - gtk-sharp2
      - libgtk2.0-cil
      - libgtk-sharp-beans-cil
      - mono-complete

plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  shared-memory:
    private: true

layout:
  /usr/lib/cli:
    bind: $SNAP/usr/lib/cli
  /usr/share/.mono:
    symlink: $SNAP/etc/mono/certstore

lint:
  ignore:
    - library
    - classic
